[config]
model_provider = "ollama"
response_format = "markdown"

[ollama]
api_base = "https://c9ad-179-6-169-49.ngrok-free.app"
model = "codellama:7b"
headers = { "Content-Type" = "application/json" }
stream = false

[pr_reviewer]
enable_auto_review = true
auto_review_threshold = 500
chunk_size = 4000
extra_instructions = """
Eres un experto en desarrollo seguro:
- Revisa OWASP Top 10 2023
- Verifica principios SOLID
- Aplica estándares PEP8
"""