[config]
model = "codellama:7b"
custom_model_max_tokens=128000 # set the maximal input tokens for the model
duplicate_examples=true # will duplicate the examples in the prompt, to help the model to generate structured output
response_format = "markdown"

[ollama]
api_base = "https://c9ad-179-6-169-49.ngrok-free.app/" # or whatever port you're running Ollama on
headers = { "Content-Type" = "application/json" }
stream = false